In [11]:
import numpy as np 
array = np.array([1,2,3,4,5])
ordinary_list = list(array)
print(ordinary_list)

[1, 2, 3, 4, 5]


In [14]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sum = np.trace(array)
print(sum)

15


In [4]:
a = [[1, 2], [3, 5]]
x = 2
result = list(filter(lambda val: val > x, [val for sublist in a for val in sublist]))
print(result)


[3, 5]


In [21]:
A = [1, 2, 3]
B = [4, 5, 6]
C = []
for i in range(len(A)):
  C.append(A[i] + B[i])
print(C) 

[5, 7, 9]


In [5]:
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix = matrix - matrix.mean(axis=1, keepdims=True)
print(matrix)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
